name: AST diff Bot

on:
  issue_comment:
    types: [created]

jobs:
  diff:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      # Step 0: Check for @diff trigger and get the URL command
      - name: Check for @diff trigger
        id: trigger
        uses: actions/github-script@v6
        with:
          script: |
            const commentBody = context.payload.comment.body;
            const regex = /@diff\s+(\S+)\s+(\S+)/;  // Match the URL and the next word
            const match = commentBody.match(regex);
            if (match) {
              core.setOutput('triggered', 'true');
              core.setOutput('url', match[1].trim()); 
              core.setOutput('screenshot', match[2] ? match[2].trim() : '');
            } else {
              core.setOutput('triggered', 'false');
            }


          
      # Step 1: Run the exporter
      - name: Running the RM action exporter
        if : ${{ steps.trigger.outputs.triggered == 'true'}}
        uses: pouryafard75/refactoringminer-astdiff-exporter@v0.8
        id: run_rm_exporter 
        with:
          OAuthToken: ${{ secrets.OAUTHTOKEN }}
          URL: ${{ steps.trigger.outputs.url }}
          screenshot: ${{ steps.trigger.outputs.screenshot }}


      - name: Echo outputs
        if : ${{ steps.trigger.outputs.triggered == 'true'}}
        run: | 
          echo ${{ steps.run_rm_exporter.outputs.screenshots_url }}
          echo "and"
          echo ${{ steps.run_rm_exporter.outputs.artifact_url }}
            

      # Step 2: Reply to the user with artifact url
      - name: Reply Artifact zip
        if: ${{ steps.trigger.outputs.triggered == 'true' && steps.trigger.outputs.screenshot == '' }}
        uses: actions/github-script@v7
        with:
          script: |
            const url = '${{ steps.trigger.outputs.url }}';
            const artifact_url = '${{ steps.run_rm_exporter.outputs.artifact_url }}'; // Add artifact_url output
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `👋 You triggered the bot with the URL: \`${url}\`. You can download it here: [Download Artifact](${artifact_url}).`
              
            })

        # Step 3: Download and extract screenshot zip
      - name: Download and extract screenshot zip
        if: ${{ steps.trigger.outputs.screenshot != null }}
        run: |
          # Download the zip file
          curl -L ${{ steps.run_rm_exporter.outputs.screenshot_url }} -o screenshots.zip
          
          # Extract the zip file
          mkdir screenshots
          unzip screenshots.zip -d screenshots

      - name: Upload image
        if: ${{ steps.trigger.outputs.screenshot != null }}
        id: upload-image-0
        uses: McCzarny/upload-image@v1.5.0
        with:
          path: screenshots/1.png
          uploadMethod: imgbb
          apiKey: '${{ secrets.IMGBB_API_KEY }}'
          
      - name: 'Comment Screenshots'
        uses: actions/github-script@0.3.0
        if: ${{ steps.trigger.outputs.screenshot != null }}
        with:
          github-token: ${{ secrets.TOKEN_GITHUB }}
          script: |
            const { issue: { number: issue_number }, repo: { owner, repo }  } = context;
            github.issues.createComment({ issue_number, owner, repo, body: 'Uploaded image:\n![0](${{steps.upload-image-0.outputs.url}})'});
